import { createDefaultZones } from "@/lib/compass/constants";
import type { ClinicalState, Prostate3DInputV1, ZoneMap } from "@/types/patient";
import type { LesionRow } from "@/types/lesion";

export function buildProstateRecord(
  S: ClinicalState,
  lesions: LesionRow[],
): Prostate3DInputV1 {
  const zones: ZoneMap = { ...createDefaultZones() };
  return {
    _schema: "prostate-3d-input-v1",
    patient: {
      age: S.age,
      psa: S.psa,
      psa_density: S.psad,
      bmi: S.bmi,
      shim: S.shim,
      ipss: S.ipss,
      dm: S.dm,
      htn: S.htn,
      cad: S.cad,
      statin: S.statin,
      smoking: S.smoking,
      exercise: S.exercise,
      pde5: S.pde5 === "daily",
    },
    prostate: {
      volume_cc: S.vol,
      dimensions_cm: null,
      median_lobe_grade: S.median_lobe_grade || null,
    },
    history: {
      prior_turp: S.prior_turp,
      prior_urolift: S.prior_urolift,
      prior_greenlight: S.prior_greenlight,
      prior_holep: S.prior_holep,
      prior_rezum: S.prior_rezum,
      prior_pelvic_radiation: S.prior_pelvic_radiation,
      urinary_retention: S.urinary_retention,
      recurrent_uti: S.recurrent_uti,
      treated_prostatitis: S.treated_prostatitis,
      biopsy_shows_inflammation: S.biopsy_shows_inflammation,
      biopsy_sessions: S.biopsy_sessions,
      crohns: S.crohns,
      ulcerative_colitis: S.ulcerative_colitis,
      diverticulitis: S.diverticulitis,
      pelvic_abscess: S.pelvic_abscess,
      hernia_mesh: S.hernia_mesh,
      rectal_fistula: S.rectal_fistula,
      radiation_proctitis: S.radiation_proctitis,
      mri_periprostatic_inflammation: S.mri_periprostatic_inflammation,
      mri_periprostatic_fat_stranding: S.mri_periprostatic_fat_stranding,
      intraop_inflammation_l: S.intraop_inflammation_l || null,
      intraop_inflammation_r: S.intraop_inflammation_r || null,
    },
    plan: {
      ns_override_l: S.plan_ns_override_l,
      ns_override_r: S.plan_ns_override_r,
      hood: S.plan_hood,
      bladder_neck_preservation: S.plan_bnp,
      sv_preservation_l: S.plan_sv_preservation_l,
      sv_preservation_r: S.plan_sv_preservation_r,
      hydrodissection_l: S.plan_hydrodissection_l,
      hydrodissection_r: S.plan_hydrodissection_r,
    },
    biopsy: {
      max_grade_group: S.gg,
      total_positive_cores: S.cores,
      total_cores: null,
      max_core_involvement_pct: S.maxcore,
      max_linear_extent_mm: S.linear_mm,
      max_pct_pattern45: S.pct45,
      has_cribriform: S.cribriform_bx,
      has_idc: S.idc_bx,
      has_pni: S.pni_bx,
      laterality: S.laterality,
      gg_left: S.gg_left,
      gg_right: S.gg_right,
      cores_left: S.cores_left,
      cores_right: S.cores_right,
      mc_left: S.mc_left,
      mc_right: S.mc_right,
      linear_left: S.linear_left,
      linear_right: S.linear_right,
      decipher_score: S.dec,
    },
    staging: {
      epe: !!S.mri_epe,
      svi: !!S.mri_svi,
      max_pirads: S.pirads,
      max_suv: S.suv || null,
      lesion_size_cm: S.mri_size > 0 ? S.mri_size : null,
      abutment: S.mri_abutment >= 0 ? S.mri_abutment : null,
      adc_mean: S.mri_adc > 0 ? S.mri_adc : null,
      epe_mus: !!S.mus_ece,
      svi_mus: !!S.mus_svi,
      psma_epe: !!S.psma_epe,
      lymph_nodes_psma: S.psma_ln ? "positive" : undefined,
    },
    zones,
    lesions,
  };
}
